### ISSUE TITLE
Add a "memory reference" field?

### ISSUE THREAD

**Issue by quinnj** [JuliaStats/NullableArrays.jl#112]
Hey all,

I've been doing a round of updates on the DataStreams packages lately (big users of this package), as well as developing the new Feather.jl package for reading/writing feather files.

In my journeys, I also started playing with a new Arrow.jl package based on the Apache Arrow project which aims to define a common in-memory "dataframe" layout (or least columnar data layout). While I think an Arrow.jl project would be awesome, the more I've dug into it, I've realized it's not a trivial implementation and even shares/overlaps with a lot of the work that's happened in this package.

For now, I want to re-invest in NullableArrays as the underlying storage, but have realized a slight limitation. A lot of workflows involve getting pointers to memory regions (mmapped or otherwise) and "reinterpreting" values out of the memory region. It's obviously ideal to not need to always copy the memory region, but just hold a reference back to it. 

The limitation is the need to hold a reference back to this memory region, while the `x.isnull` and `x.values` arrays are reinterpreted from offsets into the region.

I'd like to propose adding a single `ref::Vector{UInt8}` field to `NullableArray` that could be used to potentially hold a reference to a memory region. It would be almost completely invisible to the user, but there if needed by packages like CSV/Feather where a reference is needed.

I'm happy to put in the leg work here if everyone's on-board.

**Comment by nalimilan** [comment]
I don't fully understand your proposal. What's the use of that memory region if you also store `x.values`? In what occasions would you use `x.ref`? Couldn't that field be stored elsewhere, e.g. in a data frame-like structure which would group `NullableArrays` together?

**Comment by quinnj** [comment]
That's actually what I'm doing now in https://github.com/JuliaDB/DataStreams.jl/blob/133cccdf6a2515f3e881d58a16f706606dd7b550/src/DataStreams.jl#L184 for Data.Table, but this isn't ideal since someone could still potentially grab the NullableArrays underneath the Data.Table, drop the reference to the parent Data.Table and now the underlying NullableArrays data can potentially be invalid. It's better to keep the reference as close to the data as possible.

So more concretely, my proposal is to have the NullableArray definition be

``` julia
immutable NullableArray{T, N} <: AbstractArray{Nullable{T}, N}
    values::Array{T, N}
    isnull::Array{Bool, N}
    ref::Vector{UInt8}
end
```

The idea is that you don't/wouldn't actually need to use `x.ref` in any case, it's just there to hold a reference so that the underlying memory region doesn't get freed/unmapped.

**Comment by quinnj** [comment]
For reference, both the Arrow/feather projects include this same kind of field in their Buffer/PrimitiveArray types. See, for example, [here](https://github.com/wesm/feather/blob/d37f21da3624abf627728632c9749fffc1b42410/cpp/src/feather/buffer.h#L30).

**Comment by nalimilan** [comment]
So, to be sure I understand correctly: in your `NullableArrays`, the `values` field points inside memory allocated by the library? If so, isn't there a way to tell Julia that it cannot free that memory until the object that points inside it is removed? That sounds like an information to pass directly to the GC, not to store using additional fields in all custom types.

**Comment by quinnj** [comment]
There's no way I'm aware of to do something like that in Julia. For example, if I `m = Mmap.mmap(filename)`, that automatically adds a finalizer to `m` to call `unmap` once the reference to `m` is gone. There's no way to say, "oh hey, don't actually call that finalizer, I'll have the GC call free on that memory itself". Furthermore, I don't think that's a very common thing in any language. What's more standard, from what I've seen, is to just keep references to things that you need to ensure don't get finalized, as I mentioned above.

**Comment by nalimilan** [comment]
Yet "please don't free this area as long as Julia objects point inside it" makes a lot of sense to me. It is also more general, since your proposal implies that any type will need to get an additional field to be able to support this scenario. How are e.g. PooledDataArrays/CategoricalArrays going to work?

@carnaval Is my question regarding the GC completely unreasonable?

**Comment by quinnj** [comment]
While potentially possible, I think it gets into a realm of complexity that might be hard to reason correctly about, think about the following:
- We'd need a way to basically tell the GC that an arbitrary Julia object has a reference to another in order to increase the object-that-owns-the-memory's (actual or theoretical) "refcount"
- We'd need a way to tell GC to "unset" or at least delay any finalizers that have already been set on the Julia object holding the actual memory; this might be handled by the point above, but I'm not sure it would in all cases
- The complication with mmap specifically is that there's actually a different system call for "unmapping" an mmap memory region vs. just free-ing a malloc'd area. So you'd potentially have case where, for example, we'd have an NullableArray that didn't own it's memory that needs to be garbage-collected, so the GC would want to call `free`, which is invalid. Yet when the original Mmap object is finalized, it will call unmap

**Comment by nalimilan** [comment]
An alternative workaround would be to allow any `AbstractArray` type for the `values` field, so you could pass a `SubArray` pointing to the relevant part of the memory region. The GC would then be aware of the fact that the region (parent array) cannot be freed. That sounds like a less ad-hoc hack.

Could you ask for comments about this issue on the Julia mailing list? I'd like to be sure there's no better solution.

**Comment by quinnj** [comment]
The problem with SubArray is the inability to cross types between parent and child. i.e., the parent memory region is almost always a Vector{UInt8} which may or may not be re-interpretable to the child SubArray type on an even child byte size alignment boundary. In most of the scenarios I've seen, we're dealing with a Vector{Float64} or Vector{String} which live in the middle of the parent Vector{UInt8} region.

I don't see what the harm is. It's adding a single reference to the type and doesn't affect any other code in the repo/downstream.

**Comment by nalimilan** [comment]
That's obviously not a big deal, but we're going to have to do the same change to CategoricalArrays, and more generally I feel like it should be possible to do this kind of optimization with any array type without modifying its structure. Discussing this with Julia developers sounds reasonable.

**Comment by quinnj** [comment]
Based on @yuyichao 's comment, I started digging into what would be required to allow a SubArray as the values field. It looks kind of hairy. I'll have to think some more but it doesn't seem very straightforward to get the right type parameters, for example

``` julia
immutable NullableArray{T, N} <: AbstractArray{Nullable{T}, N}
    values::AbstractArray{T, N}
    isnull::AbstractArray{Bool, N}
end
```

isn't right because we're not getting concrete fields. But then I'm not sure how to express the same subtype constraint while also doing something like:

``` julia
immutable NullableArray{TT, N, T <: AbstractArray{TT, N}, T1 <: AbstractArray{Bool, N}} <: AbstractArray{Nullable{TT}, N}
    values::T
    isnull::T1
end
```

**Comment by nalimilan** [comment]
I think that's triangular dispatch, which isn't possible currently. But you can just do `T <: AbstractArray`, and enforce the type constraints in the inner constructor. That would really have the same effect.

**Comment by quinnj** [comment]
I still don't think I know how to express the subtype constraint though, are you saying just something like:

``` julia
immutable NullableArray{T<:AbstractArray, N} <: T
    values::T
    isnull::Array{Bool, N}
end
```

?

**Comment by nalimilan** [comment]
Something like this seems to work:

``` julia
immutable NullableArray{T, N, V<:AbstractArray} <: AbstractArray{T, N}
    values::V
    isnull::Array{Bool, N}

    function NullableArray(values::AbstractArray{T, N}, isnull::Array{Bool, N})
        new(values, isnull)
    end
end

NullableArray{T, N}(values::AbstractArray{T, N}, isnull::Array{Bool, N}) =
    NullableArray{T, N, typeof(values)}(values, isnull)

# See how efficient this can be!
dump(NullableArray(1:3, fill(false, 3)))
```

I'm always confused by inner constructors, so there might well be a simpler way of doing this.

**Comment by quinnj** [comment]
Yikes, I feel like given the complexity of coercing the constructors here, it's better off just adding the `ref` field. I feel like changing up the core inner/outer constructors like that is asking for more issues down the road.

**Comment by nalimilan** [comment]
> I feel like changing up the core inner/outer constructors like that is asking for more issues down the road.

That's not necessarily true, as inner constructors are generally not used directly. You only need to provide an outer constructor that will be used in most cases.

**Comment by quinnj** [comment]
So my main concern at this point is performance; I think the penalty of SubArray is too great to be able to rely on vs. just storing a reference and operating on a "normal" array (albeit reinterpreted).

``` julia
function t1(n)
    A = zeros(n)
    for i = 1:n
        A[i] = A[i] *2
    end
end

function t2(n)
    A = zeros(n)
    A2 = sub(A, 1:n)
    for i = 1:n
        A2[i] = A2[i] *2
    end
end

# timings
julia> @time t1(10000000)
  0.025897 seconds (6 allocations: 76.294 MB, 60.94% gc time)

julia> @time t2(10000000)
  0.093009 seconds (7 allocations: 76.294 MB, 1.15% gc time)
```

~4x hit.

**Comment by KristofferC** [comment]
@timholy has some fresh PRs to Base that might improve the subarray iterations.

**Comment by quinnj** [comment]
But not eliminate the performance hit entirely. I think we should go forward with #114 and possibly revisit later when there's a native buffer type or something similar in the language.

**Comment by nalimilan** [comment]
I'd really like to get opinions from other JuliaStats people here. So far I'm the only one to have expressed my feeling, which is kind of annoying. @davidagold?

**Comment by quinnj** [comment]
Sorry if I'm being a pain, I just happen to have a lot of free time right now and would like to push on a lot of stuff.

**Comment by nalimilan** [comment]
No problem with that. ;-) Sounds like a good conjunction, since David is starting to work on this area too since today.

**Comment by davidagold** [comment]
Aye, though it's not entirely clear what I'm doing yet. I'm not certain I understand all the issues at play, but I'm happy to give thoughts. The main drawbacks of adding a ref field seem to be: (i) not as fully general as we might like it to be (if, for instance, we could communicate more transparently with the GC), and (ii) may have implications for other data types (e.g. PooledDataArrays/CategorialArrays). Maybe it feels a little hack-ish to some. On the other hand, if it is a hack then we're in good company (Feather, Arrow). Furthermore, it doesn't seem like this would be that much of a pain to switch up if we decided that going a SubArray route is more appropriate later on. And, as Jacob says, we can not tell anybody and let him bear the breakage if we decide to nix this. I don't think that the cons outweigh the potential for progress that this might allow. But again, I'm not super familiar with these issues, so I could be convinced otherwise.

**Comment by nalimilan** [comment]
I see we're on the same line. So let's go with the hack for now. But please add a comment explaining the reason for this field, and that it will likely be removed when the `MemoryBlock`/`MemoryBuffer` type will be added to Julia.

**Comment by davidagold** [comment]
Can we close this?
