### ISSUE TITLE
Constructor from Array{Nullable} gives eltype Nullable{Nullable}

### ISSUE THREAD

**Issue by nalimilan** [JuliaStats/NullableArrays.jl#145]
Looks like `Array{Nullable}` isn't handled like `Array{Nullable{T}}`:

``` julia
julia> nm = NullableArray(Nullable[Nullable() 0.0; 0.0 1.0])
2x2 NullableArrays.NullableArray{Nullable{T},2}:
 Nullable{Union{}}()  Nullable(0.0)
 Nullable(0.0)        Nullable(1.0)

```

**Comment by davidagold** [comment]
Those should be consistent. And we should probably remark somewhere that the way to create a `NullableArray{Nullable{T}}` is by means of `NullableArray{Nullable{T}}(...)`.
