### ISSUE TITLE
Package is overwriting functions in base

### ISSUE THREAD

**Issue by galenlynch** [JuliaStats/NullableArrays.jl#196]
In julia0.6.rc1 I am getting the following warning:
`WARNING: Method definition ==(Base.Nullable{S}, Base.Nullable{T}) in module Base at nullable.jl:238 overwritten in module NullableArrays at /home/glynch/.julia/v0.6/NullableArrays/src/operators.jl:128.`

**Comment by nalimilan** [comment]
Yes, this is a known issue. In practice it won't create any problems though. See https://github.com/JuliaStats/NullableArrays.jl/pull/194.

**Comment by galenlynch** [comment]
Ah ok, thanks!
