### ISSUE TITLE
setindex is broken

### ISSUE THREAD

**Issue by johnmyleswhite** [JuliaStats/NullableArrays.jl#42]
We set the `isnull` mask too early. See example below:

``` jl
julia> using NullableArrays

julia> x = NullableArray(Int, 1)
1-element NullableArrays.NullableArray{Int64,1}:
 Nullable{Int64}()

julia> x[1] = 1.1
ERROR: InexactError()
 in setindex! at /Users/johnmyleswhite/.julia/v0.4/NullableArrays/src/indexing.jl:47

julia> x
1-element NullableArrays.NullableArray{Int64,1}:
 Nullable(13095659840)
```

**Comment by davidagold** [comment]
Ah, indeed. Switching the `values` and `isnull` assignments seems to resolve the problem. Anything more to say on this one?

**Comment by johnmyleswhite** [comment]
No, this one was surely my fault. But it suggests that we probably need to do a lot more thorough testing since I hit this within a few seconds of using the latest code.

**Comment by davidagold** [comment]
Oh for sure. I intend to go through the test suite thoroughly this week.

**Comment by davidagold** [comment]
https://github.com/johnmyleswhite/NullableArrays.jl/commit/26f2091971715d71394bd5ac68b8bd8c2b3b2df0
