### ISSUE TITLE
`isdefined` behavior for `NullableArray`s

### ISSUE THREAD

**Issue by davidagold** [JuliaStats/NullableArrays.jl#73]
This seems wrong to me:

``` julia
julia> Y = NullableArray(Array(Any, 8))
8-element NullableArray{Any,1}:
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef

julia> isdefined(Y, 1)
true

julia> Y[1]
ERROR: UndefRefError: access to undefined reference
 in getindex at /Users/David/.julia/v0.4/NullableArrays/src/indexing.jl:27
```

Of course, `isdefined(Y.values, 1)` returns `false`.

I don't know how to fix this, since `isdefined` isn't a generic function. At the very least we should include a warning somewhere in the documentation that you should only ever rely on calling `isdefined` on the `values` field of a `NullableArray`.

**Comment by davidagold** [comment]
Oh, nevermind. That's not how `isdefined` works -- the index refers to the number of the field in the type, I suppose. Closing this.

**Comment by simonster** [comment]
`isassigned` is the generic function equivalent to `isdefined`, although for some reason it's not documented.

**Comment by davidagold** [comment]
Ahah! Thanks, Simon. `isassigned` appears to give the right behavior, too.
