### ISSUE TITLE
== and missing values

### ISSUE THREAD

**Issue by nalimilan** [JuliaStats/NullableArrays.jl#74]
I would expect `==(::Nullable, ::Nullable)` to return `Nullable()` when one of the arguments is missing, instead of raising an error -- and defer the error to the point when the code calls `get` (if it does). What do you think?

For reference, the current behavior is:

``` julia
julia> Nullable(1) == Nullable(1)
Nullable(true)

julia> Nullable(1) == Nullable(2)
Nullable(false)

julia> Nullable(1) == Nullable()
ERROR: 
 in == at /home/milan/.julia/NullableArrays/src/operators.jl:55
```

PS: I guess `==(::Nullable, ::Nullable)` is supposed to get merged into Base at some point?

**Comment by nalimilan** [comment]
This issue is actually closely related to https://github.com/JuliaLang/julia/issues/13207. If `Nullable() == Nullable()` continues to raise an error, there's little point for `==(::Nullable, ::Nullable)` to return  a `Nullable{Bool}`: better return a `Bool`. Then support for `Nullable` in `if` wouldn't be required.

I'm not saying that's a good idea, but that's another data point in that discussion.

**Comment by johnmyleswhite** [comment]
Let's just submit a PR to Base that uses the natural lifting semantics for `==`.

I really don't want us to waste our time discussing these kinds of issues until we have a more polished package that people can use with confidence that it's both correct and performant.

I find these theory-world level design debates fairly poisonous and I've wasted too much of my life negotiating semantics when I should have just been writing more code.

**Comment by nalimilan** [comment]
By "natural lifting semantics", do you mean my proposal, or the current behaviour in NullableArrays.jl?

**Comment by johnmyleswhite** [comment]
I mean the semantics we use for all the math operations `f(x::Nullable...)` is `NULL` if and only if any of the inputs is `NULL`.

**Comment by nalimilan** [comment]
I would be fine with that.

**Comment by nalimilan** [comment]
I've just found out this:

``` julia
julia> Nullable(1) == Nullable()
ERROR: 
 [inlined code] from error.jl:22
 in == at /home/milan/.julia/NullableArrays.jl/src/operators.jl:55

julia> Nullable(1) == Nullable{Int}()
Nullable{Bool}()
```

The bug is only the check for `isbits()`, which fails for `Union{}`. I suggest replacing all `isbits()` checks in operators.jl with `isbitsorbottom(x) = isbits(x) || x == Union{}`. This will also allow things like `Nullable(1) + Nullable() == Nullable()`. OK?
