### ISSUE TITLE
In a NullableArray, if na[i] = true, is it ok that values[i] = #undef?

### ISSUE THREAD

**Issue by amellnik** [JuliaStats/NullableArrays.jl#90]
Does code that works with NullableArrays need to be ready to deal with undefined values in in the `values` field?  It looks like this is true from the code, but I didn't see it spelled out in the doc, and wanted to make sure that  https://github.com/JuliaDB/SQLite.jl/issues/88 is not due to the input being a malformed NullableArray.

**Comment by nalimilan** [comment]
I think undefined values should be supported, as there is no point in initializing elements corresponding to missing entries (which might be costly for e.g. non-scalar types).

**Comment by davidagold** [comment]
@amellnik There is no guarantee that indexing directly into the `values` field of a `NullableArray` object will be safe. Attempts to do so, or, say, to copy the `values` field wholesale, should be preceded by checks.

Apart from the potential costliness of initializing elements of `NullableArray`s of non-bits eltypes, I don't see how one would go about doing so in an extensible, non-arbitrary manner.

**Comment by amellnik** [comment]
That's what I assumed, thanks!
