### ISSUE TITLE
Make NullableArrays Precompilable or block precompilation

### ISSUE THREAD

**Issue by JeremyRubin** [JuliaStats/NullableArrays.jl#91]
System segfaults when trying to use precompiled copy of NullableArrays, so either precompiliation should be disabled or the module should be modified to make it work.

**Comment by nalimilan** [comment]
`using NullableArrays` doesn't segfault here. Could you print your `versioninfo()`?

**Comment by JeremyRubin** [comment]
Julia Version 0.4.0
Commit 0ff703b\* (2015-10-08 06:20 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin14.3.0)
  CPU: Intel(R) Core(TM) i7-2620M CPU @ 2.70GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

**Comment by JeremyRubin** [comment]
But it also doesn't precompile, correct? Mine only segfaults when I precompile it.

**Comment by JeremyRubin** [comment]
Eg, add `__precompile__()` to module NullableArrays

```
julia> using NullableArrays
INFO: Precompiling module NullableArrays...
WARNING: replacing module NullableArrays

signal (11): Segmentation fault: 11
jl_deserialize_lambdas_from_mod at /Users/jeremyrubin/builds/julia/julia-0.4.0/src/dump.c:1578
_jl_restore_incremental at /Users/jeremyrubin/builds/julia/julia-0.4.0/src/dump.c:2209
jl_restore_incremental at /Users/jeremyrubin/builds/julia/julia-0.4.0/src/dump.c:2277
_require_from_serialized at loading.jl:84
jlcall__require_from_serialized_21454 at  (unknown line)
jl_apply at /Users/jeremyrubin/builds/julia/julia-0.4.0/src/gf.c:1691
require at ./loading.jl:251
jlcall_require_19291 at /Users/jeremyrubin/builds/julia/julia-0.4.0/usr/lib/julia/sys.dylib (unknown line)
jl_apply at /Users/jeremyrubin/builds/julia/julia-0.4.0/src/./julia.h:1325
eval_import_path at /Users/jeremyrubin/builds/julia/julia-0.4.0/src/toplevel.c:393
jl_toplevel_eval_in at /Users/jeremyrubin/builds/julia/julia-0.4.0/src/builtins.c:579
eval_user_input at REPL.jl:62
jlcall_eval_user_input_21334 at  (unknown line)
jl_apply at /Users/jeremyrubin/builds/julia/julia-0.4.0/src/gf.c:1691
anonymous at REPL.jl:92
jl_apply at /Users/jeremyrubin/builds/julia/julia-0.4.0/src/task.c:241
[1]    75622 segmentation fault  julia
```

**Comment by JeremyRubin** [comment]
(To save you time -- future reader, if you try the above, delete julia/lib/v.04/NullableArrays.ji after this because precompile doesn't remove the failed attempt)

**Comment by nalimilan** [comment]
0.4.1 and git master don't crash here even when adding `__precompile__()`. Could you try with one of these versions?

**Comment by JeremyRubin** [comment]
you're right --fixed!
